<template>
  <section class="case-detail-page"><header class="page-heading"><div><el-button link type="primary" @click="router.push('/cases')">返回案件列表</el-button><h2>风险案件详情</h2></div></header><div v-if="loading"><el-skeleton :rows="8" animated/></div><div v-else-if="error" class="state-panel"><el-alert title="风险案件加载失败，请稍后重试。" type="error" :closable="false" show-icon/><el-button type="primary" @click="loadCase">重新加载</el-button></div><template v-else-if="item"><el-card class="panel-card" shadow="never"><template #header><strong>案件基本信息</strong></template><el-descriptions :column="2" border><el-descriptions-item label="案件编号">{{ item.caseId }}</el-descriptions-item><el-descriptions-item label="风险等级"><el-tag :type="riskTag(item.riskLevel)">{{ item.riskLevel }}</el-tag></el-descriptions-item><el-descriptions-item label="案件状态"><el-tag :type="statusTag(item.status)">{{ item.status }}</el-tag></el-descriptions-item><el-descriptions-item label="发现时间">{{ item.discoveredAt }}</el-descriptions-item><el-descriptions-item label="业务 A">{{ item.businessA.loanId }}</el-descriptions-item><el-descriptions-item label="业务 B">{{ item.businessB.loanId }}</el-descriptions-item></el-descriptions></el-card><el-card class="panel-card" shadow="never"><template #header><strong>影像对比</strong></template><div class="comparison"><div><p>业务 A 面签照片</p><img :src="imageUrl(item.businessA)" alt="业务 A 面签照片"/></div><strong class="similarity">{{ item.similarity.toFixed(2) }}%<small>相似度</small></strong><div><p>业务 B 面签照片</p><img :src="imageUrl(item.businessB)" alt="业务 B 面签照片"/></div></div></el-card><section class="detail-grid"><el-card class="panel-card" shadow="never"><template #header><strong>相似度分析</strong></template><ul><li v-for="entry in item.similarityAnalysis" :key="entry">{{ entry }}</li></ul></el-card><el-card class="panel-card" shadow="never"><template #header><strong>风险原因</strong></template><ul><li v-for="entry in item.riskReasons" :key="entry">{{ entry }}</li></ul></el-card></section><div class="actions"><el-button v-if="item.status === '待核查'" type="primary" @click="changeStatus('核查中')">开始核查</el-button><template v-else-if="item.status === '核查中'"><el-button type="danger" @click="changeStatus('已确认')">确认风险</el-button><el-button @click="changeStatus('已排除')">标记为正常</el-button></template></div></template></section>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { getRiskCase, updateRiskCaseStatus } from '../api/cases'
import { getFileUrl } from '../api'

const route = useRoute(); const router = useRouter(); const item = ref(null); const loading = ref(true); const error = ref(false)
const imageUrl = (business) => business.imageUrl || getFileUrl(item.value.taskId, business.imagePath)
const riskTag = (level) => ({ 高风险: 'danger', 中风险: 'warning', 低风险: 'success' }[level] || 'info'); const statusTag = (status) => ({ 待核查: 'warning', 核查中: 'primary', 已确认: 'danger', 已排除: 'success' }[status] || 'info')
const loadCase = async () => { loading.value = true; error.value = false; try { item.value = (await getRiskCase(route.params.id)).data } catch { error.value = true; item.value = null } finally { loading.value = false } }
const changeStatus = async (status) => { item.value = (await updateRiskCaseStatus(item.value.caseId, status)).data; ElMessage.success(`案件状态已更新为${status}`) }
onMounted(loadCase)
</script>

<style scoped>
.case-detail-page{max-width:1200px;margin:0 auto}.page-heading{margin:4px 0 20px}.page-heading h2{margin:10px 0 0;color:var(--text-primary);font-size:24px}.panel-card{margin-bottom:20px;border-color:var(--border-color);background:var(--bg-card)}.comparison{display:grid;grid-template-columns:1fr 150px 1fr;align-items:center;gap:20px;text-align:center}.comparison p{color:var(--text-secondary);font-size:13px}.comparison img{width:100%;max-height:320px;object-fit:cover;margin-top:10px;border-radius:var(--radius-sm)}.similarity{color:var(--accent);font-size:28px}.similarity small{display:block;margin-top:6px;color:var(--text-muted);font-size:12px}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.detail-grid ul{margin:0;padding-left:20px;color:var(--text-secondary);line-height:2}.actions{display:flex;justify-content:flex-end;gap:10px}.state-panel{display:flex;gap:16px}.state-panel .el-alert{flex:1}@media(max-width:720px){.comparison{grid-template-columns:1fr}.detail-grid{grid-template-columns:1fr}}
</style>
