<template>
  <section class="cases-page">
    <header class="page-heading"><div><h2>风险案件中心</h2><p>集中查看影像相似度检测发现的疑似风险案件。</p></div><el-tag v-if="isMock" type="info" effect="plain">MOCK · 后端无数据时展示</el-tag></header>
    <section class="summary-grid"><el-card v-for="item in summaryItems" :key="item.label" shadow="never"><span>{{ item.label }}</span><strong>{{ item.value }}</strong></el-card></section>
    <el-card class="filter-card" shadow="never"><el-form :model="filters" class="case-filter" @submit.prevent="loadCases"><el-form-item label="案件编号"><el-input v-model="filters.caseId" clearable placeholder="请输入案件编号"/></el-form-item><el-form-item label="业务编号"><el-input v-model="filters.businessId" clearable placeholder="请输入业务编号"/></el-form-item><el-form-item label="风险等级"><el-select v-model="filters.riskLevel" clearable placeholder="全部"><el-option v-for="item in riskOptions" :key="item" :label="item" :value="item"/></el-select></el-form-item><el-form-item label="处理状态"><el-select v-model="filters.status" clearable placeholder="全部"><el-option v-for="item in statusOptions" :key="item" :label="item" :value="item"/></el-select></el-form-item><el-form-item label="日期范围"><el-date-picker v-model="filters.dateRange" type="daterange" value-format="YYYY-MM-DD" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期"/></el-form-item><div class="filter-actions"><el-button type="primary" native-type="submit" :loading="loading">查询</el-button><el-button type="primary" @click="resetFilters">重置</el-button></div></el-form></el-card>
    <el-card class="table-card" shadow="never"><template #header><div class="table-title">案件列表 <span>共 {{ items.length }} 条</span></div></template><div v-if="error" class="state-panel"><el-alert title="风险案件加载失败，请稍后重试。" type="error" :closable="false" show-icon/><el-button type="primary" @click="loadCases">重新加载</el-button></div><el-table v-else-if="items.length || loading" v-loading="loading" :data="items" :header-cell-style="tableHeaderStyle"><el-table-column prop="caseId" label="案件编号" min-width="185"/><el-table-column label="关联业务" min-width="210"><template #default="{ row }"><div>{{ row.businessA.loanId }}</div><div>{{ row.businessB.loanId }}</div></template></el-table-column><el-table-column label="相似度" width="110"><template #default="{ row }">{{ row.similarity.toFixed(2) }}%</template></el-table-column><el-table-column label="风险等级" width="105"><template #default="{ row }"><el-tag :type="riskTag(row.riskLevel)">{{ row.riskLevel }}</el-tag></template></el-table-column><el-table-column label="风险原因" min-width="230"><template #default="{ row }">{{ row.riskReasons[0] }}</template></el-table-column><el-table-column prop="discoveredAt" label="发现时间" min-width="165"/><el-table-column label="处理状态" width="105"><template #default="{ row }"><el-tag :type="statusTag(row.status)">{{ row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="router.push(`/cases/${row.caseId}`)">查看详情</el-button></template></el-table-column></el-table><el-empty v-else description="暂无符合条件的风险案件"><el-button type="primary" @click="resetFilters">重置筛选</el-button></el-empty></el-card>
  </section>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getRiskCases } from '../api/cases'

const router = useRouter(); const loading = ref(false); const error = ref(false); const items = ref([]); const isMock = ref(false)
const filters = reactive({ caseId: '', businessId: '', riskLevel: '', status: '', dateRange: [] })
const riskOptions = ['高风险', '中风险', '低风险']; const statusOptions = ['待核查', '核查中', '已确认', '已排除']
const tableHeaderStyle = { background: 'var(--bg-card-hover)', color: 'var(--text-secondary)', fontWeight: 600 }
const summaryItems = computed(() => [{ label: '全部案件', value: items.value.length }, { label: '高风险', value: items.value.filter((item) => item.riskLevel === '高风险').length }, { label: '中风险', value: items.value.filter((item) => item.riskLevel === '中风险').length }, { label: '低风险', value: items.value.filter((item) => item.riskLevel === '低风险').length }, { label: '待核查', value: items.value.filter((item) => item.status === '待核查').length }])
const riskTag = (level) => ({ 高风险: 'danger', 中风险: 'warning', 低风险: 'success' }[level] || 'info'); const statusTag = (status) => ({ 待核查: 'warning', 核查中: 'primary', 已确认: 'danger', 已排除: 'success' }[status] || 'info')
const loadCases = async () => { loading.value = true; error.value = false; try { const res = await getRiskCases(filters); items.value = res.data.records; isMock.value = Boolean(res.mock) } catch { error.value = true; items.value = [] } finally { loading.value = false } }
const resetFilters = () => { filters.caseId = ''; filters.businessId = ''; filters.riskLevel = ''; filters.status = ''; filters.dateRange = []; loadCases() }
onMounted(loadCases)
</script>

<style scoped>
.cases-page{max-width:1400px;margin:0 auto}.page-heading{display:flex;justify-content:space-between;gap:16px;margin:4px 0 20px}.page-heading h2{margin:0 0 7px;color:var(--text-primary);font-size:24px}.page-heading p{margin:0;color:var(--text-secondary);font-size:14px}.summary-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin-bottom:20px}.summary-grid .el-card{border-color:var(--border-color);background:var(--bg-card)}.summary-grid :deep(.el-card__body){display:flex;flex-direction:column;gap:8px}.summary-grid span{color:var(--text-secondary);font-size:13px}.summary-grid strong{color:var(--text-primary);font-size:25px}.filter-card,.table-card{margin-bottom:20px;border-color:var(--border-color);background:var(--bg-card)}.case-filter{display:flex;flex-wrap:wrap;align-items:flex-end;gap:0 16px}.case-filter :deep(.el-form-item){margin-bottom:0}.case-filter :deep(.el-input){width:180px}.case-filter :deep(.el-select){width:130px}.case-filter :deep(.el-date-editor){width:270px}.filter-actions{display:flex;gap:10px}.table-title{font-size:16px;font-weight:600;color:var(--text-primary)}.table-title span{margin-left:8px;color:var(--text-muted);font-size:13px;font-weight:400}.state-panel{display:flex;gap:16px}.state-panel .el-alert{flex:1}@media(max-width:1100px){.summary-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.page-heading{flex-direction:column}.summary-grid{grid-template-columns:repeat(2,1fr)}.case-filter :deep(.el-form-item){width:100%}.case-filter :deep(.el-input),.case-filter :deep(.el-select),.case-filter :deep(.el-date-editor){width:100%}}
</style>
